# Generated by Django 4.2.11 on 2024-06-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_businessgrant_assestgrant_agricgrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricgrant',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assestgrant',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessgrant',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
